### PR TITLE
Sortable trait removed, fixes #9.

### LINKED ISSUE #9: Laravel 5.1: Sortable trait problem with order method ?
Since laravel 5.1, my groups and items are no more sorted by weight, am I alone with this issue ?

### PR DESCRIPTION
**Pull request by sdebacker**

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
Also tested with L5?

**Comment by nWidart** [comment]
If it's a breaking change, maybe just keep the current tag for l5, and after this merge, start tagging for 5.1 only ?

**Comment by sdebacker** [comment]
Just tested with Laravel 5 and it works perfectly.
This isn't a breaking change as I only use the sortBy method included in Laravel collection class in place of the order method that was in the Sortable trait (this method was also calling sortBy but in a different way).

**Comment by nWidart** [comment]
:+1:

**Comment by patrickbrouwers** [comment]
Found the change in Laravel: https://github.com/laravel/framework/commit/e57cb0d968841bd67bf2b8eb589d4479de924ee1

`sortBy` now returns a new Collection, no longer modifies the original.

**Comment by sdebacker** [comment]
Ok I didn't saw that.

**Pull request merged**
