### PR TITLE
illuminate/html is deprecated and not used in this package.

### PR DESCRIPTION
**Pull request by sdebacker**

### CODE REVIEW

**Comment by patrickbrouwers** [comment]
No idea how it ended up in their, thanks! :)

**Comment by nWidart** [comment]
:+1:

**Comment by nWidart** [comment]
Isn't it needed though? If so maybe use `laravelcollective/html` ?

**Comment by nWidart** [comment]
I see that `use Illuminate\Support\Facades\URL;` being used.

**Comment by patrickbrouwers** [comment]
Did a quick scan, no html is used. And URl is in routing I think.

**Comment by sdebacker** [comment]
Nice, let's 1.0.1 !

**Comment by patrickbrouwers** [comment]
Already did ;)

**Comment by nWidart** [comment]
Cool, my bad. :smiley:

**Pull request merged**
